version: '3.9'

services:

  postgres:
    image: postgres:15-alpine
    container_name: incentive_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - incentive_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incentive_backend
    restart: always
    env_file: .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    depends_on:
      postgres:
        condition: service_healthy        # waits for postgres to be ready
    expose:
      - "8000"                            # internal only, not to outside
    networks:
      - incentive_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "http://51.21.150.176/api"              # multi-stage, outputs built static files
    container_name: incentive_frontend
    restart: always
    expose:
      - "80"
    networks:
      - incentive_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: incentive_nginx
    restart: always
    ports:
      - "80:80"                           # only this is exposed to internet
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - incentive_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  incentive_network:
    driver: bridge